# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  push:
    branches:
      - main  # Adjust this branch name as needed

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16  # You can adjust the Node.js version

    - name: Install Dependencies
      run: npm install

    - name: Build React Application
      run: npm run build

    - name: Build Jekyll Site
      run: |
        gem install bundler
        bundle install
        bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
